server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-route
              uri: http://localhost:8081
              predicates:
                - Path=/api/identity/**
            - id: account-route
              uri: http://localhost:8082
              predicates:
                - Path=/api/accounts/**
            - id: transaction-route
              uri: http://localhost:8083
              predicates:
                - Path=/api/transactions/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

